bf16: true
cutoff_len: 4096
dataset: '[Easy Dataset] [x5dr29YqfRpJ] Alpaca'
dataset_dir: C:\Users\Administrator\AppData\Roaming\easy-dataset\local-db\x5dr29YqfRpJ\
ddp_timeout: 180000000
do_train: true
double_quantization: true
enable_thinking: true
eval_steps: 100
eval_strategy: steps
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 10000
model_name_or_path: C:\Users\Administrator\.cache\modelscope\hub\models\Qwen\Qwen3-0.6B
num_train_epochs: 3.0
optim: adamw_torch
output_dir: saves\Qwen3-0.6B-Thinking\lora\train_2025-08-05-22-53-12
packing: false
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
quantization_bit: 8
quantization_method: bnb
report_to: none
save_steps: 100
stage: sft
template: qwen3
trust_remote_code: true
val_size: 0.1
warmup_steps: 0
